apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenjava-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenjava
  template:
    metadata:
      labels:
        app: mavenjava
    spec:
      containers:
        - name: mavenjava-container
          image: yazankhdoc1/maven-jenkins   # image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080           # app runs here
---
apiVersion: v1
kind: Service
metadata:
  name: mavenjava-service
spec:
  type: NodePort
  selector:
    app: mavenjava
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080   # optional 
